name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UC0VfiydI7hA3YDhnFRKWKJw
          lang: en
          max_videos: 6
          card_width: 250
          border_radius: 5
          background_color: "#0d1117"
          title_color: "#ffffff"
          stats_color: "#dedede"
          author_name: "GitHub Actions"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "docs(readme): Update YouTube cards"
          readme_path: README.md
